# Documentation: http://docs.travis-ci.com/user/languages/julia
if: (type == push) OR (type == pull_request AND fork == true)
language: julia
notifications:
  email: false
julia:
  - 1.4
  - nightly
addons:
  apt:
    packages:
      - python3-matplotlib
os:
  - linux
  - osx
  - windows
arch:
  - x64
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.4
      script: |
        julia --project=docs -e '
          using Pkg
          pkg"add http://github.com/JuliaAtoms/AtomicLevels.jl"
          pkg"add http://github.com/JuliaAtoms/EnergyExpressions.jl"
          pkg"add http://github.com/JuliaAtoms/AngularMomentumAlgebra.jl#revamp"
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
